title: Oinam Github
remote_theme: oinam/oinam-jekyll

footer:
  credit: true
  custom: false

markdown: kramdown
permalink: pretty

plugins:
  - jekyll-remote-theme
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - CNAME
  - Gemfile
  - Gemfile.lock
  - gemfiles/
  - README.*